### ISSUE TITLE
Enable type checking for library users

### ISSUE THREAD

**Issue by robin-nitrokey** [NXPmicro/spsdk#24]
As far as I see, the spsdk library has extensive type annotations which is really useful.  Unfortunately, it does not have a [`py.typed` marker file](https://www.python.org/dev/peps/pep-0561/#packaging-type-information), so library users cannot automatically re-use these annotations.  Have you considered enabling these type checks?

**Comment by mstarecek** [comment]
Hi, this sounds like a great idea. We'll add the marker file ASAP

**Comment by mstarecek** [comment]
The py.typed file was added in release 1.6.0.
