### ISSUE TITLE
LICENSE file is missing from pypi sdist tarball/ LICENSE file issues

### ISSUE THREAD

**Issue by dvzrv** [NXPmicro/spsdk#26]
Hi! I'm looking into packaging this project for Arch Linux.

We usually rely on sdist tarballs on pypi.org and I noticed that your LICENSE file is missing from it.
The sdist tarball being a source distribution needs to retain the copyright notice (as per [clause one](https://github.com/NXPmicro/spsdk/blob/f18a90049f2df1197f7126b0aacd543ade66eb9c/LICENSE#L6-L7)) and I need to retain the copyright notice in a binary distribution (as per [clause two](https://github.com/NXPmicro/spsdk/blob/f18a90049f2df1197f7126b0aacd543ade66eb9c/LICENSE#L9-L11), which is also part of our packaging guidelines).
The source files contain an SPDX license identifier and a copyright notice (e.g. https://github.com/NXPmicro/spsdk/blob/f18a90049f2df1197f7126b0aacd543ade66eb9c/spsdk/exceptions.py#L4-L6), but that does not cover the first clause of the license and without the license file, distributors can not satisfy clause two either.

As a sidenote: When looking at the [SPDX definition for BSD 3-Clause "New" or "Revised"](https://spdx.org/licenses/BSD-3-Clause.html), it states, that the license should carry the `Copyright (c) <year> <owner>. All rights reserved.` string at the top of the license file (but yours does not do that).
As there is no standard license header (for source files) for this license, I believe that carrying the copyright notice in the header of each source file (e.g. https://github.com/NXPmicro/spsdk/blob/f18a90049f2df1197f7126b0aacd543ade66eb9c/spsdk/exceptions.py#L4) is superfluous, but it is required in your LICENSE file!

**Comment by mstarecek** [comment]
Hi. This will be solved in the next release (scheduled for early next week)
