### ISSUE TITLE
Support for parsing master boot images

### ISSUE THREAD

**Issue by robin-nitrokey** [NXPmicro/spsdk#31]
` spsdk.image.mbimg.MasterBootImage.parse` is currently not implemented.  I think it would make sense to either remove the method altogether until it is implemented, or at least mention in the documentation that it does not work.  Do you have plans for implementing this function?

**Comment by mstarecek** [comment]
Hi, I always thought that the docstring contains such a message. Guess we need to double-check our pylint and pydocstyle settings :)
We do intend to implement this feature. However, currently, it has low priority. For now, we'll just add NotImplemented info into the method's docstring.

**Comment by robin-nitrokey** [comment]
Okay, thank you!

**Comment by mstarecek** [comment]
Docstring (and generated docs) now properly state if a method is not implemented.
