### ISSUE TITLE
Change type annotations for RawHid.enumerate

### ISSUE THREAD

**Issue by robin-nitrokey** [NXPmicro/spsdk#32]
Could the type annotation for [`RawHid.enumerate`](https://github.com/NXPmicro/spsdk/blob/master/spsdk/mboot/interfaces/usb.py#L246) be changed to `Sequence[RawHid]`?

**Comment by mstarecek** [comment]
That's a good point, we can return the exact type from all of the `scan_*` functions to make it a little more user-friendly. As long as they inherit from `Interface` everything should be fine.
