### ISSUE TITLE
Type annotations for McuBoot.get_property/PropertyTag not working

### ISSUE THREAD

**Issue by robin-nitrokey** [NXPmicro/spsdk#33]
This code causes the following mypy error:

```
self.device.get_property(PropertyTag.UNIQUE_DEVICE_IDENT)
```

```
Argument 1 to "get_property" of "McuBoot" has incompatible type "Tuple[int, str, str]"; expected "PropertyTag"
```

I assume this is related to the `easy_enum` type annotations.

**Comment by mstarecek** [comment]
I believe this is caused by the missing .pyi file. It will be added soon.

**Comment by mstarecek** [comment]
Missing .pyi file was added into PyPI tarball. The issue should be resolved.
Could you please confirm that it's working on your end? Thanks

**Comment by marekvi95** [comment]
The issue has been resolved by adding the missing .pyi file.
