### ISSUE TITLE
SPSDK 1.6.0 and 1.5.0 fails after MarkupSafe 2.1.0 release

### ISSUE THREAD

**Issue by ivan2angelov** [NXPmicro/spsdk#39]
SPSDK requirements.txt needs:
jinja2>=2.11,<3
jinja2 happily pulls Markupsafe larger or equal to 2.0, see:
https://github.com/pallets/jinja/blob/main/setup.py

Very recently https://pypi.org/project/MarkupSafe/2.1.0/ was released (link https://markupsafe.palletsprojects.com/en/2.1.x/changes/):
"Remove soft_unicode, which was previously deprecated. Use soft_str instead. [#261](https://github.com/pallets/markupsafe/pull/261)"
As a result when SPSDK uses jinja2 there is an exception due to missing import:
ImportError: cannot import name 'soft_unicode' from markupsafe

Suggestion: could you fix jinja2 version in SPSDK to a version that will guarantee operation of the SPSDK?

**Comment by Gargy007** [comment]
Hello,
 thanks for good point, you nicely confirm just our findings from today morning. The issue will be solved in release SPSDK v1.6.1 which will be release this month.

**Comment by Gargy007** [comment]
Hi, it should be. I moved the jinja2 to Hitler version.

Gargy

Dne st 16. 3. 2022 15:36 uživatel Ivan Angelov ***@***.***>
napsal:

**Comment by marekvi95** [comment]
Closing the issue, Jijna version has been bumped to 3.0. Upper boundary is now being handled by CI system.
