### ISSUE TITLE
Test fails because it uses pyyaml wrong

### ISSUE THREAD

**Issue by dvzrv** [NXPmicro/spsdk#45]
Upon trying to package 1.7.0 for Arch Linux I ran the test suite.
Unfortunately [test_generate_template](https://github.com/NXPmicro/spsdk/blob/053fb9ab76c9f4b9e280c17c93634654ed3641ea/tests/nxpcertgen/test_certgen.py#L273) uses pyyaml wrong, by attempting to use `load()` without a loader (see [documentation](https://pyyaml.org/wiki/PyYAMLDocumentation)). It is unclear how that test has ever passed NXP's internal CI, as at least the latest versions of pyyaml do not support calling `load()` like that.

**Comment by mwsk** [comment]
This has been solved in 1.7.1 release using: safe_load()
data = yaml.safe_load(f)
